// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKCvYicCDn6uj2MUUsABtZ7Ot_37X9fks',
    appId: '1:9810382406:web:aff1adf88d68b4ab340447',
    messagingSenderId: '9810382406',
    projectId: 'palate-path-4281',
    authDomain: 'palate-path-4281.firebaseapp.com',
    storageBucket: 'palate-path-4281.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKCvYicCDn6uj2MUUsABtZ7Ot_37X9fks',
    appId: '1:9810382406:android:0922ebb282558554340447',
    messagingSenderId: '9810382406',
    projectId: 'palate-path-4281',
    storageBucket: 'palate-path-4281.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKCvYicCDn6uj2MUUsABtZ7Ot_37X9fks',
    appId: '1:9810382406:ios:899f5e46c753361a340447',
    messagingSenderId: '9810382406',
    projectId: 'palate-path-4281',
    storageBucket: 'palate-path-4281.appspot.com',
    iosBundleId: 'com.example.palatePath',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKCvYicCDn6uj2MUUsABtZ7Ot_37X9fks',
    appId: '1:9810382406:ios:899f5e46c753361a340447',
    messagingSenderId: '9810382406',
    projectId: 'palate-path-4281',
    storageBucket: 'palate-path-4281.appspot.com',
    iosBundleId: 'com.example.palatePath',
  );
}
